/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AbridgedVideoView
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-06T16:49:42.215909-04:00[America/New_York]")
public class AbridgedVideoView {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_VIEWER_OS_FAMILY = "viewer_os_family";
  @SerializedName(SERIALIZED_NAME_VIEWER_OS_FAMILY)
  private String viewerOsFamily;

  public static final String SERIALIZED_NAME_VIEWER_APPLICATION_NAME = "viewer_application_name";
  @SerializedName(SERIALIZED_NAME_VIEWER_APPLICATION_NAME)
  private String viewerApplicationName;

  public static final String SERIALIZED_NAME_VIDEO_TITLE = "video_title";
  @SerializedName(SERIALIZED_NAME_VIDEO_TITLE)
  private String videoTitle;

  public static final String SERIALIZED_NAME_TOTAL_ROW_COUNT = "total_row_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_ROW_COUNT)
  private Long totalRowCount;

  public static final String SERIALIZED_NAME_PLAYER_ERROR_MESSAGE = "player_error_message";
  @SerializedName(SERIALIZED_NAME_PLAYER_ERROR_MESSAGE)
  private String playerErrorMessage;

  public static final String SERIALIZED_NAME_PLAYER_ERROR_CODE = "player_error_code";
  @SerializedName(SERIALIZED_NAME_PLAYER_ERROR_CODE)
  private String playerErrorCode;

  public static final String SERIALIZED_NAME_ERROR_TYPE_ID = "error_type_id";
  @SerializedName(SERIALIZED_NAME_ERROR_TYPE_ID)
  private Integer errorTypeId;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_VIEW_START = "view_start";
  @SerializedName(SERIALIZED_NAME_VIEW_START)
  private String viewStart;

  public static final String SERIALIZED_NAME_VIEW_END = "view_end";
  @SerializedName(SERIALIZED_NAME_VIEW_END)
  private String viewEnd;


  public AbridgedVideoView id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public AbridgedVideoView viewerOsFamily(String viewerOsFamily) {
    
    this.viewerOsFamily = viewerOsFamily;
    return this;
  }

   /**
   * Get viewerOsFamily
   * @return viewerOsFamily
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getViewerOsFamily() {
    return viewerOsFamily;
  }


  public void setViewerOsFamily(String viewerOsFamily) {
    this.viewerOsFamily = viewerOsFamily;
  }


  public AbridgedVideoView viewerApplicationName(String viewerApplicationName) {
    
    this.viewerApplicationName = viewerApplicationName;
    return this;
  }

   /**
   * Get viewerApplicationName
   * @return viewerApplicationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getViewerApplicationName() {
    return viewerApplicationName;
  }


  public void setViewerApplicationName(String viewerApplicationName) {
    this.viewerApplicationName = viewerApplicationName;
  }


  public AbridgedVideoView videoTitle(String videoTitle) {
    
    this.videoTitle = videoTitle;
    return this;
  }

   /**
   * Get videoTitle
   * @return videoTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVideoTitle() {
    return videoTitle;
  }


  public void setVideoTitle(String videoTitle) {
    this.videoTitle = videoTitle;
  }


  public AbridgedVideoView totalRowCount(Long totalRowCount) {
    
    this.totalRowCount = totalRowCount;
    return this;
  }

   /**
   * Get totalRowCount
   * @return totalRowCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTotalRowCount() {
    return totalRowCount;
  }


  public void setTotalRowCount(Long totalRowCount) {
    this.totalRowCount = totalRowCount;
  }


  public AbridgedVideoView playerErrorMessage(String playerErrorMessage) {
    
    this.playerErrorMessage = playerErrorMessage;
    return this;
  }

   /**
   * Get playerErrorMessage
   * @return playerErrorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlayerErrorMessage() {
    return playerErrorMessage;
  }


  public void setPlayerErrorMessage(String playerErrorMessage) {
    this.playerErrorMessage = playerErrorMessage;
  }


  public AbridgedVideoView playerErrorCode(String playerErrorCode) {
    
    this.playerErrorCode = playerErrorCode;
    return this;
  }

   /**
   * Get playerErrorCode
   * @return playerErrorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlayerErrorCode() {
    return playerErrorCode;
  }


  public void setPlayerErrorCode(String playerErrorCode) {
    this.playerErrorCode = playerErrorCode;
  }


  public AbridgedVideoView errorTypeId(Integer errorTypeId) {
    
    this.errorTypeId = errorTypeId;
    return this;
  }

   /**
   * Get errorTypeId
   * @return errorTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getErrorTypeId() {
    return errorTypeId;
  }


  public void setErrorTypeId(Integer errorTypeId) {
    this.errorTypeId = errorTypeId;
  }


  public AbridgedVideoView countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public AbridgedVideoView viewStart(String viewStart) {
    
    this.viewStart = viewStart;
    return this;
  }

   /**
   * Get viewStart
   * @return viewStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getViewStart() {
    return viewStart;
  }


  public void setViewStart(String viewStart) {
    this.viewStart = viewStart;
  }


  public AbridgedVideoView viewEnd(String viewEnd) {
    
    this.viewEnd = viewEnd;
    return this;
  }

   /**
   * Get viewEnd
   * @return viewEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getViewEnd() {
    return viewEnd;
  }


  public void setViewEnd(String viewEnd) {
    this.viewEnd = viewEnd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbridgedVideoView abridgedVideoView = (AbridgedVideoView) o;
    return Objects.equals(this.id, abridgedVideoView.id) &&
        Objects.equals(this.viewerOsFamily, abridgedVideoView.viewerOsFamily) &&
        Objects.equals(this.viewerApplicationName, abridgedVideoView.viewerApplicationName) &&
        Objects.equals(this.videoTitle, abridgedVideoView.videoTitle) &&
        Objects.equals(this.totalRowCount, abridgedVideoView.totalRowCount) &&
        Objects.equals(this.playerErrorMessage, abridgedVideoView.playerErrorMessage) &&
        Objects.equals(this.playerErrorCode, abridgedVideoView.playerErrorCode) &&
        Objects.equals(this.errorTypeId, abridgedVideoView.errorTypeId) &&
        Objects.equals(this.countryCode, abridgedVideoView.countryCode) &&
        Objects.equals(this.viewStart, abridgedVideoView.viewStart) &&
        Objects.equals(this.viewEnd, abridgedVideoView.viewEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, viewerOsFamily, viewerApplicationName, videoTitle, totalRowCount, playerErrorMessage, playerErrorCode, errorTypeId, countryCode, viewStart, viewEnd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbridgedVideoView {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    viewerOsFamily: ").append(toIndentedString(viewerOsFamily)).append("\n");
    sb.append("    viewerApplicationName: ").append(toIndentedString(viewerApplicationName)).append("\n");
    sb.append("    videoTitle: ").append(toIndentedString(videoTitle)).append("\n");
    sb.append("    totalRowCount: ").append(toIndentedString(totalRowCount)).append("\n");
    sb.append("    playerErrorMessage: ").append(toIndentedString(playerErrorMessage)).append("\n");
    sb.append("    playerErrorCode: ").append(toIndentedString(playerErrorCode)).append("\n");
    sb.append("    errorTypeId: ").append(toIndentedString(errorTypeId)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    viewStart: ").append(toIndentedString(viewStart)).append("\n");
    sb.append("    viewEnd: ").append(toIndentedString(viewEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

