/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AssetMetadata
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AssetMetadata {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_CREATOR_ID = "creator_id";
  @SerializedName(SERIALIZED_NAME_CREATOR_ID)
  private String creatorId;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "external_id";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private String externalId;


  public AssetMetadata title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The video title. Max 512 code points.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The video title. Max 512 code points.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public AssetMetadata creatorId(String creatorId) {
    
    this.creatorId = creatorId;
    return this;
  }

   /**
   * This is an identifier you provide to keep track of the creator of the video. Max 128 code points.
   * @return creatorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is an identifier you provide to keep track of the creator of the video. Max 128 code points.")

  public String getCreatorId() {
    return creatorId;
  }


  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }


  public AssetMetadata externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * This is an identifier you provide to link the video to your own data. Max 128 code points.
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is an identifier you provide to link the video to your own data. Max 128 code points.")

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetMetadata assetMetadata = (AssetMetadata) o;
    return Objects.equals(this.title, assetMetadata.title) &&
        Objects.equals(this.creatorId, assetMetadata.creatorId) &&
        Objects.equals(this.externalId, assetMetadata.externalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, creatorId, externalId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetMetadata {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

