/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mux.sdk.models.GetAssetOrLiveStreamIdResponseDataObject;
import com.mux.sdk.models.PlaybackPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetAssetOrLiveStreamIdResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-15T16:07:59.745206-04:00[America/New_York]")
public class GetAssetOrLiveStreamIdResponseData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_POLICY = "policy";
  @SerializedName(SERIALIZED_NAME_POLICY)
  private PlaybackPolicy policy;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private GetAssetOrLiveStreamIdResponseDataObject _object;


  public GetAssetOrLiveStreamIdResponseData id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The Playback ID used to retrieve the corresponding asset or the live stream ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Playback ID used to retrieve the corresponding asset or the live stream ID")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public GetAssetOrLiveStreamIdResponseData policy(PlaybackPolicy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PlaybackPolicy getPolicy() {
    return policy;
  }


  public void setPolicy(PlaybackPolicy policy) {
    this.policy = policy;
  }


  public GetAssetOrLiveStreamIdResponseData _object(GetAssetOrLiveStreamIdResponseDataObject _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * Get _object
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetAssetOrLiveStreamIdResponseDataObject getObject() {
    return _object;
  }


  public void setObject(GetAssetOrLiveStreamIdResponseDataObject _object) {
    this._object = _object;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAssetOrLiveStreamIdResponseData getAssetOrLiveStreamIdResponseData = (GetAssetOrLiveStreamIdResponseData) o;
    return Objects.equals(this.id, getAssetOrLiveStreamIdResponseData.id) &&
        Objects.equals(this.policy, getAssetOrLiveStreamIdResponseData.policy) &&
        Objects.equals(this._object, getAssetOrLiveStreamIdResponseData._object);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, policy, _object);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAssetOrLiveStreamIdResponseData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

