/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Insight
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-06T13:02:50.965402-04:00[America/New_York]")
public class Insight {
  public static final String SERIALIZED_NAME_TOTAL_WATCH_TIME = "total_watch_time";
  @SerializedName(SERIALIZED_NAME_TOTAL_WATCH_TIME)
  private Long totalWatchTime;

  public static final String SERIALIZED_NAME_TOTAL_VIEWS = "total_views";
  @SerializedName(SERIALIZED_NAME_TOTAL_VIEWS)
  private Long totalViews;

  public static final String SERIALIZED_NAME_NEGATIVE_IMPACT_SCORE = "negative_impact_score";
  @SerializedName(SERIALIZED_NAME_NEGATIVE_IMPACT_SCORE)
  private Float negativeImpactScore;

  public static final String SERIALIZED_NAME_METRIC = "metric";
  @SerializedName(SERIALIZED_NAME_METRIC)
  private Double metric;

  public static final String SERIALIZED_NAME_FILTER_VALUE = "filter_value";
  @SerializedName(SERIALIZED_NAME_FILTER_VALUE)
  private String filterValue;

  public static final String SERIALIZED_NAME_FILTER_COLUMN = "filter_column";
  @SerializedName(SERIALIZED_NAME_FILTER_COLUMN)
  private String filterColumn;


  public Insight totalWatchTime(Long totalWatchTime) {
    
    this.totalWatchTime = totalWatchTime;
    return this;
  }

   /**
   * Get totalWatchTime
   * @return totalWatchTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTotalWatchTime() {
    return totalWatchTime;
  }


  public void setTotalWatchTime(Long totalWatchTime) {
    this.totalWatchTime = totalWatchTime;
  }


  public Insight totalViews(Long totalViews) {
    
    this.totalViews = totalViews;
    return this;
  }

   /**
   * Get totalViews
   * @return totalViews
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTotalViews() {
    return totalViews;
  }


  public void setTotalViews(Long totalViews) {
    this.totalViews = totalViews;
  }


  public Insight negativeImpactScore(Float negativeImpactScore) {
    
    this.negativeImpactScore = negativeImpactScore;
    return this;
  }

   /**
   * Get negativeImpactScore
   * @return negativeImpactScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getNegativeImpactScore() {
    return negativeImpactScore;
  }


  public void setNegativeImpactScore(Float negativeImpactScore) {
    this.negativeImpactScore = negativeImpactScore;
  }


  public Insight metric(Double metric) {
    
    this.metric = metric;
    return this;
  }

   /**
   * Get metric
   * @return metric
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getMetric() {
    return metric;
  }


  public void setMetric(Double metric) {
    this.metric = metric;
  }


  public Insight filterValue(String filterValue) {
    
    this.filterValue = filterValue;
    return this;
  }

   /**
   * Get filterValue
   * @return filterValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFilterValue() {
    return filterValue;
  }


  public void setFilterValue(String filterValue) {
    this.filterValue = filterValue;
  }


  public Insight filterColumn(String filterColumn) {
    
    this.filterColumn = filterColumn;
    return this;
  }

   /**
   * Get filterColumn
   * @return filterColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFilterColumn() {
    return filterColumn;
  }


  public void setFilterColumn(String filterColumn) {
    this.filterColumn = filterColumn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Insight insight = (Insight) o;
    return Objects.equals(this.totalWatchTime, insight.totalWatchTime) &&
        Objects.equals(this.totalViews, insight.totalViews) &&
        Objects.equals(this.negativeImpactScore, insight.negativeImpactScore) &&
        Objects.equals(this.metric, insight.metric) &&
        Objects.equals(this.filterValue, insight.filterValue) &&
        Objects.equals(this.filterColumn, insight.filterColumn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalWatchTime, totalViews, negativeImpactScore, metric, filterValue, filterColumn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Insight {\n");
    sb.append("    totalWatchTime: ").append(toIndentedString(totalWatchTime)).append("\n");
    sb.append("    totalViews: ").append(toIndentedString(totalViews)).append("\n");
    sb.append("    negativeImpactScore: ").append(toIndentedString(negativeImpactScore)).append("\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("    filterValue: ").append(toIndentedString(filterValue)).append("\n");
    sb.append("    filterColumn: ").append(toIndentedString(filterColumn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

