/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mux.sdk.models.Annotation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ListAnnotationsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ListAnnotationsResponse {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private java.util.List<Annotation> data = null;

  public static final String SERIALIZED_NAME_TOTAL_ROW_COUNT = "total_row_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_ROW_COUNT)
  private Integer totalRowCount;

  public static final String SERIALIZED_NAME_TIMEFRAME = "timeframe";
  @SerializedName(SERIALIZED_NAME_TIMEFRAME)
  private java.util.List<Integer> timeframe = null;


  public ListAnnotationsResponse data(java.util.List<Annotation> data) {
    
    this.data = data;
    return this;
  }

  public ListAnnotationsResponse addDataItem(Annotation dataItem) {
    if (this.data == null) {
      this.data = new java.util.ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public java.util.List<Annotation> getData() {
    return data;
  }


  public void setData(java.util.List<Annotation> data) {
    this.data = data;
  }


  public ListAnnotationsResponse totalRowCount(Integer totalRowCount) {
    
    this.totalRowCount = totalRowCount;
    return this;
  }

   /**
   * Total number of annotations available
   * @return totalRowCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total number of annotations available")

  public Integer getTotalRowCount() {
    return totalRowCount;
  }


  public void setTotalRowCount(Integer totalRowCount) {
    this.totalRowCount = totalRowCount;
  }


  public ListAnnotationsResponse timeframe(java.util.List<Integer> timeframe) {
    
    this.timeframe = timeframe;
    return this;
  }

  public ListAnnotationsResponse addTimeframeItem(Integer timeframeItem) {
    if (this.timeframe == null) {
      this.timeframe = new java.util.ArrayList<>();
    }
    this.timeframe.add(timeframeItem);
    return this;
  }

   /**
   * Start and end unix timestamps for the data range
   * @return timeframe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start and end unix timestamps for the data range")

  public java.util.List<Integer> getTimeframe() {
    return timeframe;
  }


  public void setTimeframe(java.util.List<Integer> timeframe) {
    this.timeframe = timeframe;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAnnotationsResponse listAnnotationsResponse = (ListAnnotationsResponse) o;
    return Objects.equals(this.data, listAnnotationsResponse.data) &&
        Objects.equals(this.totalRowCount, listAnnotationsResponse.totalRowCount) &&
        Objects.equals(this.timeframe, listAnnotationsResponse.timeframe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, totalRowCount, timeframe);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAnnotationsResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    totalRowCount: ").append(toIndentedString(totalRowCount)).append("\n");
    sb.append("    timeframe: ").append(toIndentedString(timeframe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

