/*
 * Mux API
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mux.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mux.sdk.models.CreateStaticRenditionRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest {
  public static final String SERIALIZED_NAME_STATIC_RENDITIONS = "static_renditions";
  @SerializedName(SERIALIZED_NAME_STATIC_RENDITIONS)
  private java.util.List<CreateStaticRenditionRequest> staticRenditions = null;


  public UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest staticRenditions(java.util.List<CreateStaticRenditionRequest> staticRenditions) {
    
    this.staticRenditions = staticRenditions;
    return this;
  }

  public UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest addStaticRenditionsItem(CreateStaticRenditionRequest staticRenditionsItem) {
    if (this.staticRenditions == null) {
      this.staticRenditions = new java.util.ArrayList<>();
    }
    this.staticRenditions.add(staticRenditionsItem);
    return this;
  }

   /**
   * Get staticRenditions
   * @return staticRenditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public java.util.List<CreateStaticRenditionRequest> getStaticRenditions() {
    return staticRenditions;
  }


  public void setStaticRenditions(java.util.List<CreateStaticRenditionRequest> staticRenditions) {
    this.staticRenditions = staticRenditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest updateLiveStreamNewAssetSettingsStaticRenditionsRequest = (UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest) o;
    return Objects.equals(this.staticRenditions, updateLiveStreamNewAssetSettingsStaticRenditionsRequest.staticRenditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(staticRenditions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateLiveStreamNewAssetSettingsStaticRenditionsRequest {\n");
    sb.append("    staticRenditions: ").append(toIndentedString(staticRenditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

